-- 1. Create Tables
CREATE TABLE IF NOT EXISTS trl_categories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL UNIQUE,
    display_order INT NOT NULL DEFAULT 0,
    is_virtual BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS trl_sources (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    url TEXT NOT NULL UNIQUE,
    type TEXT NOT NULL DEFAULT 'rss' CHECK (type IN ('rss', 'html', 'newsletter')),
    category TEXT DEFAULT 'Tech Brief',
    is_preset BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Seed Categories
INSERT INTO trl_categories (name, display_order, is_virtual) VALUES
('Just Now', 0, true),
('Weekly Top', 10, true),
('Local Brief', 20, false),
('National Brief', 30, false),
('World Brief', 40, false),
('Tech Brief', 50, false),
('Science Brief', 60, false),
('Business Brief', 70, false),
('Finance Brief', 80, false),
('Lifestyle Brief', 90, false),
('Health Brief', 100, false),
('Travel Brief', 110, false),
('Entertainment Brief', 120, false)
ON CONFLICT (name) DO UPDATE SET 
    display_order = EXCLUDED.display_order,
    is_virtual = EXCLUDED.is_virtual;

-- 3. Seed Sources
INSERT INTO trl_sources (name, url, type, category, is_preset) VALUES
-- World Brief
('BBC News', 'https://feeds.bbci.co.uk/news/rss.xml', 'rss', 'World Brief', true),
('Reuters', 'https://www.reuters.com/tools/rss', 'rss', 'World Brief', true),
('Al Jazeera', 'https://www.aljazeera.com/xml/rss/all.xml', 'rss', 'World Brief', true),
('The Guardian', 'https://www.theguardian.com/world/rss', 'rss', 'World Brief', true),
('The New York Times World', 'https://rss.nytimes.com/services/xml/rss/nyt/World.xml', 'rss', 'World Brief', true),
('Associated Press', 'https://feeds.apnews.com/ap/rss', 'rss', 'World Brief', true),
('France 24', 'https://www.france24.com/en/rss', 'rss', 'World Brief', true),
('DW', 'https://www.dw.com/en/rss', 'rss', 'World Brief', true),
('South China Morning Post', 'https://www.scmp.com/rss', 'rss', 'World Brief', true),
('NPR International', 'https://www.npr.org/rss/podcast.php?id=510298', 'rss', 'World Brief', true),
-- National Brief
('The New York Times', 'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml', 'rss', 'National Brief', true),
('Washington Post', 'https://feeds.washingtonpost.com/rss/national', 'rss', 'National Brief', true),
('CNN', 'https://rss.cnn.com/rss/cnn_topstories.rss', 'rss', 'National Brief', true),
('Wall Street Journal', 'https://feeds.a.dj.com/rss/RSSWorldNews.xml', 'rss', 'National Brief', true),
('USA Today', 'https://www.usatoday.com/rss', 'rss', 'National Brief', true),
('NPR', 'https://feeds.npr.org/1001/rss.xml', 'rss', 'National Brief', true),
('CBS News', 'https://www.cbsnews.com/rss', 'rss', 'National Brief', true),
('ABC News', 'https://abcnews.go.com/abcnews/topstoriesrss', 'rss', 'National Brief', true),
('NBC News', 'https://www.nbcnews.com/rss', 'rss', 'National Brief', true),
('Axios', 'https://www.axios.com/rss', 'rss', 'National Brief', true),
-- Tech Brief
('TechCrunch', 'https://techcrunch.com/feed/', 'rss', 'Tech Brief', true),
('The Verge', 'https://www.theverge.com/rss/index.xml', 'rss', 'Tech Brief', true),
('Wired', 'https://www.wired.com/feed/rss', 'rss', 'Tech Brief', true),
('Engadget', 'https://www.engadget.com/rss.xml', 'rss', 'Tech Brief', true),
('Gizmodo', 'https://gizmodo.com/rss', 'rss', 'Tech Brief', true),
('Ars Technica', 'https://arstechnica.com/feed/', 'rss', 'Tech Brief', true),
('CNET', 'https://www.cnet.com/rss/', 'rss', 'Tech Brief', true),
('Bloomberg Technology', 'https://feeds.bloomberg.com/technology/news.rss', 'rss', 'Tech Brief', true),
('MIT Technology Review', 'https://www.technologyreview.com/feed/', 'rss', 'Tech Brief', true),
('ZDNet', 'https://www.zdnet.com/topic/rss.xml', 'rss', 'Tech Brief', true),
-- Science Brief
('Scientific American', 'https://www.scientificamerican.com/feed/', 'rss', 'Science Brief', true),
('Nature', 'https://www.nature.com/nature.rss', 'rss', 'Science Brief', true),
('Science Magazine', 'https://www.science.org/rss/current.xml', 'rss', 'Science Brief', true),
('New Scientist', 'https://www.newscientist.com/feed/', 'rss', 'Science Brief', true),
('National Geographic', 'https://www.nationalgeographic.com/science/rss', 'rss', 'Science Brief', true),
('Popular Science', 'https://www.popsci.com/rss', 'rss', 'Science Brief', true),
('Discover', 'https://www.discovermagazine.com/feed', 'rss', 'Science Brief', true),
('Quanta Magazine', 'https://www.quantamagazine.org/feed/', 'rss', 'Science Brief', true),
('BBC Science', 'https://www.bbc.com/news/science_and_environment/rss.xml', 'rss', 'Science Brief', true),
('Smithsonian Magazine', 'https://www.smithsonianmag.com/rss/', 'rss', 'Science Brief', true),
-- Business Brief
('Bloomberg Business', 'https://feeds.bloomberg.com/markets/news.rss', 'rss', 'Business Brief', true),
('CNBC Business', 'https://www.cnbc.com/id/100003114/device/rss/rss.html', 'rss', 'Business Brief', true),
('The Economist Business', 'https://www.economist.com/business/rss.xml', 'rss', 'Business Brief', true),
('Wall Street Journal Business', 'https://feeds.a.dj.com/rss/RSSMarketsMain.xml', 'rss', 'Business Brief', true),
('Financial Times Business', 'https://www.ft.com/rss/business', 'rss', 'Business Brief', true),
('Forbes', 'https://www.forbes.com/business/feed/', 'rss', 'Business Brief', true),
('Business Insider', 'https://www.businessinsider.com/rss', 'rss', 'Business Brief', true),
('Reuters Business', 'https://www.reuters.com/rss/business', 'rss', 'Business Brief', true),
('Fortune', 'https://fortune.com/feed/', 'rss', 'Business Brief', true),
('Harvard Business Review', 'https://hbr.org/feed', 'rss', 'Business Brief', true),
-- Finance Brief
('CNBC Finance', 'https://www.cnbc.com/id/100003114/device/rss/rss.html', 'rss', 'Finance Brief', true),
('Bloomberg Finance', 'https://feeds.bloomberg.com/markets/news.rss', 'rss', 'Finance Brief', true),
('Wall Street Journal Markets', 'https://feeds.a.dj.com/rss/RSSMarketsMain.xml', 'rss', 'Finance Brief', true),
('Financial Times Markets', 'https://www.ft.com/rss/markets', 'rss', 'Finance Brief', true),
('Reuters Markets', 'https://www.reuters.com/rss/markets', 'rss', 'Finance Brief', true),
('Yahoo Finance', 'https://finance.yahoo.com/rss/topstories', 'rss', 'Finance Brief', true),
('MarketWatch', 'https://www.marketwatch.com/rss', 'rss', 'Finance Brief', true),
('Investopedia', 'https://www.investopedia.com/rss', 'rss', 'Finance Brief', true),
('Barron’s', 'https://www.barrons.com/rss', 'rss', 'Finance Brief', true),
('Morningstar', 'https://www.morningstar.com/rss', 'rss', 'Finance Brief', true),
-- Health Brief
('Mayo Clinic', 'https://newsnetwork.mayoclinic.org/feed/', 'rss', 'Health Brief', true),
('WebMD', 'https://rssfeeds.webmd.com/rss/rss.aspx?RSSSource=RSS_PUBLIC', 'rss', 'Health Brief', true),
('Harvard Health', 'https://www.health.harvard.edu/feed', 'rss', 'Health Brief', true),
('The Lancet', 'https://www.thelancet.com/rss', 'rss', 'Health Brief', true),
('New England Journal of Medicine', 'https://www.nejm.org/rss', 'rss', 'Health Brief', true),
('Kaiser Health News', 'https://khn.org/feed/', 'rss', 'Health Brief', true),
('BBC Health', 'https://www.bbc.com/news/health/rss.xml', 'rss', 'Health Brief', true),
('NPR Health', 'https://www.npr.org/rss/podcast.php?id=510298', 'rss', 'Health Brief', true),
('CDC', 'https://www.cdc.gov/rss', 'rss', 'Health Brief', true),
('WHO', 'https://www.who.int/rss', 'rss', 'Health Brief', true),
-- Lifestyle Brief
('Vogue', 'https://www.vogue.com/feed/rss', 'rss', 'Lifestyle Brief', true),
('GQ', 'https://www.gq.com/feed/rss', 'rss', 'Lifestyle Brief', true),
('The New York Times Style', 'https://rss.nytimes.com/services/xml/rss/nyt/Style.xml', 'rss', 'Lifestyle Brief', true),
('Elle', 'https://www.elle.com/rss', 'rss', 'Lifestyle Brief', true),
('Harper’s Bazaar', 'https://www.harpersbazaar.com/rss', 'rss', 'Lifestyle Brief', true),
('Vanity Fair', 'https://www.vanityfair.com/feed/rss', 'rss', 'Lifestyle Brief', true),
('Refinery29', 'https://www.refinery29.com/rss', 'rss', 'Lifestyle Brief', true),
('Bon Appétit', 'https://www.bonappetit.com/feed', 'rss', 'Lifestyle Brief', true),
('Apartment Therapy', 'https://www.apartmenttherapy.com/rss', 'rss', 'Lifestyle Brief', true),
('Travel + Leisure Lifestyle', 'https://www.travelandleisure.com/feed', 'rss', 'Lifestyle Brief', true),
-- Travel Brief
('Lonely Planet', 'https://www.lonelyplanet.com/feed', 'rss', 'Travel Brief', true),
('National Geographic Travel', 'https://www.nationalgeographic.com/travel/rss', 'rss', 'Travel Brief', true),
('Travel + Leisure', 'https://www.travelandleisure.com/feed', 'rss', 'Travel Brief', true),
('Condé Nast Traveler', 'https://www.cntraveler.com/feed/rss', 'rss', 'Travel Brief', true),
('AFAR', 'https://www.afar.com/rss', 'rss', 'Travel Brief', true),
('BBC Travel', 'https://www.bbc.com/travel/rss', 'rss', 'Travel Brief', true),
('The Points Guy', 'https://thepointsguy.com/feed/', 'rss', 'Travel Brief', true),
('Rough Guides', 'https://www.roughguides.com/feed/', 'rss', 'Travel Brief', true),
('Rick Steves', 'https://www.ricksteves.com/rss', 'rss', 'Travel Brief', true),
('Frommer’s', 'https://www.frommers.com/rss', 'rss', 'Travel Brief', true),
-- Entertainment Brief
('Variety', 'https://variety.com/feed/', 'rss', 'Entertainment Brief', true),
('The Hollywood Reporter', 'https://www.hollywoodreporter.com/feed/', 'rss', 'Entertainment Brief', true),
('Entertainment Weekly', 'https://ew.com/feed/', 'rss', 'Entertainment Brief', true),
('Deadline', 'https://deadline.com/feed/', 'rss', 'Entertainment Brief', true),
('TMZ', 'https://www.tmz.com/rss.xml', 'rss', 'Entertainment Brief', true),
('People', 'https://people.com/rss', 'rss', 'Entertainment Brief', true),
('Rolling Stone', 'https://www.rollingstone.com/feed/', 'rss', 'Entertainment Brief', true),
('Billboard', 'https://www.billboard.com/rss', 'rss', 'Entertainment Brief', true),
('E! Online', 'https://www.eonline.com/rss', 'rss', 'Entertainment Brief', true),
('IMDb News', 'https://www.imdb.com/news/rss', 'rss', 'Entertainment Brief', true),
-- Local Brief
('New York Times (NY)', 'https://rss.nytimes.com/services/xml/rss/nyt/NYRegion.xml', 'rss', 'Local Brief', true),
('LA Times (LA)', 'https://www.latimes.com/rss', 'rss', 'Local Brief', true),
('Chicago Tribune (Chicago)', 'https://www.chicagotribune.com/rss', 'rss', 'Local Brief', true),
('Boston Globe (Boston)', 'https://www.bostonglobe.com/rss', 'rss', 'Local Brief', true),
('SF Chronicle (San Francisco)', 'https://www.sfchronicle.com/rss', 'rss', 'Local Brief', true),
('Houston Chronicle (Houston)', 'https://www.houstonchronicle.com/rss', 'rss', 'Local Brief', true),
('Miami Herald (Miami)', 'https://www.miamiherald.com/rss', 'rss', 'Local Brief', true),
('Seattle Times (Seattle)', 'https://www.seattletimes.com/rss', 'rss', 'Local Brief', true),
('Atlanta Journal-Constitution (Atlanta)', 'https://www.ajc.com/rss', 'rss', 'Local Brief', true),
('Dallas Morning News (Dallas)', 'https://www.dallasnews.com/rss', 'rss', 'Local Brief', true)
ON CONFLICT (url) DO UPDATE SET 
    category = EXCLUDED.category,
    name = EXCLUDED.name,
    is_preset = EXCLUDED.is_preset;
